# Generated by Django 6.0.4 on 2026-04-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('food', 'Food & Dining'), ('bills', 'Bills & Utilities'), ('transport', 'Transport'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('payroll', 'Payroll'), ('subscription', 'Subscription'), ('vendor', 'Vendor Payment'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
    ]
