# Generated by Django 6.0.4 on 2026-04-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('wants_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('savings_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('business', 'Business Revenue'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
    ]
