# Generated by Django 6.0.4 on 2026-04-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budgetrule_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stocks', 'Stocks'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Cryptocurrency'), ('fixed_deposit', 'Fixed Deposit'), ('gold', 'Gold'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_invested', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
    ]
